ShuffleBoard
redshiftrobotics/8032 pull request #14
Opened 2020-01-18 04:02 UTC by nautilushell

- Add shuffleboard support

- Comments and cleanup

- Minor bug fixes to `limelight.py`

2020-01-18 04:04 UTC, nautilushell commented on .gitignore
> +/tools/
Not necessary

2020-01-18 04:06 UTC, nautilushell commented on limelight.py
>          """Sets the camera mode"""
I guess I just forgot the function definition

2020-01-22 17:30 UTC, zoecarver requested changes
This looks like it should be three different PRs. The most important thing is that we fix master. Please make a quick patch to do that so I can approve it and we can get that in. Then you can rebase this off master. 

Also, `NeuralNetwork` should be another patch and probably shouldn't be in master until we're actually using it.

2020-01-22 17:30 UTC, zoecarver commented on colorSensorV3.py
> +        return -62
What's this number? Add a comment.

2020-01-22 17:30 UTC, zoecarver commented on components/neuralNetwork.py
> +@author: Julian Allchin
Say what this does.

2020-01-22 17:30 UTC, zoecarver commented on components/neuralNetwork.py
> +    return (1/(1+np.exp(-x)))
Spaces please.

2020-01-22 17:30 UTC, zoecarver commented on components/neuralNetwork.py
> +"""ACTIVATION Functions"""
Why are there two types of comments here?

2020-01-22 17:30 UTC, zoecarver commented on components/neuralNetwork.py
> +     sig=sigmoid(z)
Spaces please

2020-01-22 17:30 UTC, zoecarver commented on components/neuralNetwork.py
> +# quadratic cost function and its derivative
Same as above

2020-01-22 20:08 UTC, zoecarver commented
Fixed master in b1b37f2 so you don't have to do that.

2020-01-28 00:41 UTC, closed without merging